"""empty message

Revision ID: 25dd26402ac3
Revises: b20295f2f26c
Create Date: 2023-04-20 10:22:08.660737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25dd26402ac3'
down_revision = 'b20295f2f26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('seconds', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('seconds')
        batch_op.drop_column('minutes')

    # ### end Alembic commands ###
