"""empty message

Revision ID: 33576f7f50b8
Revises: 25dd26402ac3
Create Date: 2023-04-20 10:23:03.901108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33576f7f50b8'
down_revision = '25dd26402ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('seconds', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('seconds')
        batch_op.drop_column('minutes')

    # ### end Alembic commands ###
