"""empty message

Revision ID: b20295f2f26c
Revises: d0bfc461ee5b
Create Date: 2023-03-13 23:33:00.427087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20295f2f26c'
down_revision = 'd0bfc461ee5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.add_column(sa.Column('success', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.drop_column('success')

    # ### end Alembic commands ###
