"""empty message

Revision ID: d0bfc461ee5b
Revises: 
Create Date: 2023-03-13 20:57:28.711503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bfc461ee5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gamer')),
    sa.UniqueConstraint('login', name=op.f('uq_gamer_login'))
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gamer_id'], ['gamer.id'], name=op.f('fk_session_gamer_id_gamer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_num', sa.Integer(), nullable=False),
    sa.Column('digits_count', sa.Integer(), nullable=False),
    sa.Column('numbers_count', sa.Integer(), nullable=False),
    sa.Column('minimum', sa.Integer(), nullable=False),
    sa.Column('maximum', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_level_session_id_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_level'))
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n1', sa.Integer(), nullable=False),
    sa.Column('n2', sa.Integer(), nullable=False),
    sa.Column('n3', sa.Integer(), nullable=True),
    sa.Column('n4', sa.Integer(), nullable=True),
    sa.Column('n5', sa.Integer(), nullable=True),
    sa.Column('n6', sa.Integer(), nullable=True),
    sa.Column('n7', sa.Integer(), nullable=True),
    sa.Column('n8', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], name=op.f('fk_answers_level_id_level')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers'))
    )
    op.create_table('numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n1', sa.Integer(), nullable=False),
    sa.Column('n2', sa.Integer(), nullable=False),
    sa.Column('n3', sa.Integer(), nullable=True),
    sa.Column('n4', sa.Integer(), nullable=True),
    sa.Column('n5', sa.Integer(), nullable=True),
    sa.Column('n6', sa.Integer(), nullable=True),
    sa.Column('n7', sa.Integer(), nullable=True),
    sa.Column('n8', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], name=op.f('fk_numbers_level_id_level')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_numbers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('numbers')
    op.drop_table('answers')
    op.drop_table('level')
    op.drop_table('session')
    op.drop_table('gamer')
    # ### end Alembic commands ###
